# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191015_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
    ]
